### ISSUE TITLE
index alignments

### ISSUE THREAD

**Issue by patriktyppo** [bvn-architecture/transformative#24]
some align fixing
![image](https://cloud.githubusercontent.com/assets/11640099/6859713/468d770c-d470-11e4-8e7b-e86b47f34676.png)

**Comment by notionparallax** [comment]
so, to turn that into things to do:
- [ ] align the stalk of the Ts with the edge of the images
- [ ] Move the 4 down and left so that the bottom of the circle aligns with the midline of the subtitle
- [ ] align "BVN transformative" in the header with the edge of the editorial text
- [ ] align the H of home on the heading links with edge of the images

The structure of the site means that the 'project stories' bit is in the bottom row. This is required so that the editorial and the first image can swap.

![image](https://cloud.githubusercontent.com/assets/1865196/6860176/df2ff2fc-d478-11e4-86bc-d91e3a34f3c2.png)

It wasn't possible to swap those two bits over without using javascript.

**Comment by patriktyppo** [comment]
ok. We'll keep the "project stories" where it is then. What about the footer, what elements do we need in there?
